theme: jekyll-theme-hacker
title: Ben Ni
description: Love all the things related to technology, want real world experience in a place where skills can be fully utilized
logo: logo.jpg
show_downloads: false
google_analytics: UA-154959453-1