theme: jekyll-theme-minimal
title: Ben Ni
description: love all the things related to technology and want real world experience in a place where my skills can be fully utilized
logo: logo.jpg
show_downloads: false
google_analytics: UA-154959453-1